[package]
name = "egake-server"
description = "Static-bundle and server configuration primitives for egake"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
axum = "0.8"
egake-resource = { path = "../egake-resource" }
percent-encoding = "2.3"
serde_json = "1.0"
tokio = { version = "1.43", features = ["net", "rt-multi-thread"] }

[lints]
workspace = true

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
